Add StufController and bind it to ThingService to reproduce failing tests
By this commit, some tests are failed with `NoMethodError` For example,
<NoMethodError: undefined method `get_contextual_field_error_fail' for #<StuffController:0x007f8029c9fb20>>

The reason is that current impl does not expect being called `#bind`
more than once for a single service. If calling twice, it causes overriding all
the methods of the service with the different controller.